version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - /mnt/media/downloads/:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        # - OPENVPN_CONFIG=default
        - NORDVPN_COUNTRY=US
        - NORDVPN_CATEGORY=legacy_p2p
        - NORDVPN_PROTOCOL=udp
        - OPENVPN_USERNAME=UsKT8Nf6WuLkvA9zEAL6Z71k
        - OPENVPN_PASSWORD=6LukpZoExmizFLP48zaDgpqn
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.8.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn

 jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /mnt/media/appdata/jackett:/config
        - /mnt/media/downloads/watch:/downloads
    restart: unless-stopped

 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /mnt/media/appdata/radarr:/config
        - /mnt/media/media/movies:/movies
        - /mnt/media/downloads/completed:/downloads
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /mnt/media/appdata/sonarr:/config
        - /mnt/media/media/tv:/tv
        - /mnt/media/downloads/completed:/downloads
    restart: unless-stopped

 lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /mnt/media/appdata/lidarr:/config
        - /mnt/media/media/music:/music
        - /mnt/media/downloads/completed:/downloads
    restart: unless-stopped

 lazylibrarian:
    image: linuxserver/lazylibrarian
    network_mode: "service:transmission-openvpn"
    container_name: lazylibrarian
    environment:
        - PUID=1000
        - PGID=100
         - TZ=America/New_York
        #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
        - /mnt/media/appdata/lazylibrarian:/config
        - /mnt/media/downloads/completed:/downloads
        - /mnt/media/media/ebooks:/books
    restart: unless-stopped


